eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8090

spring:
  application:
    name: students
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./databases/students
    username: mustard
    password: 206207
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true # Format SQL statements in logs
        use_sql_comments: true # Include SQL comments in logs

